import type { ExerciseId, ExerciseProfile } from "./types";
import { defineExercise } from "./exercise-profile";
import { rom } from "./rom-profile";
import { tempo } from "./tempo-profile";
import { joints, primary, secondary, stabilizer } from "./joint-profile";
import { symmetry } from "./symmetry-profile";
import { risk, sensitivity } from "./risk-profile";
import { mistake } from "./common-mistakes";

/** The exercise metadata catalog. One entry per ExerciseId — this is the
 *  only file that needs a new entry to onboard a future exercise; every
 *  other module in this folder is generic over ExerciseProfile. */
export const EXERCISE_CATALOG: Record<ExerciseId, ExerciseProfile> = {
  squat: defineExercise({
    id: "squat",
    displayName: "Squat",
    aliases: ["squat"],
    category: "lower-body-compound",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "lower",
    rom: rom("knee", [70, 170], "hip crease at or below the top of the knee (parallel or below)"),
    tempo: tempo([1.5, 3], [1, 2], "high", [0, 1]),
    joints: joints([primary("knee"), primary("hip"), secondary("ankle"), stabilizer("core")]),
    symmetry: symmetry("high", false),
    risk: risk([
      sensitivity("knee-valgus", "high"),
      sensitivity("lumbar-spine", "moderate"),
    ]),
    commonMistakes: [
      mistake("heels-lifting", "Heels lifting", "Weight shifts onto the toes/forefoot instead of staying mid-foot.", "moderate"),
      mistake("knee-valgus", "Knees caving", "Knees collapse inward on the way up, especially near failure.", "major"),
      mistake("forward-lean", "Forward lean", "Torso pitches forward, shifting load off the hips and onto the lower back.", "moderate"),
      mistake("insufficient-depth", "Insufficient depth", "Reps stop short of parallel, cutting the working range short.", "moderate"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["out of the hole (bottom third)", "mid-range sticking point"],
    compensationPatterns: ["knee valgus under fatigue", "forward torso lean to offset ankle/hip mobility limits"],
    coachingPriorities: ["maintain depth before adding load", "keep knees tracking over the toes", "brace the core throughout"],
    expectedStability: "moderate",
    typicalFatiguePattern: "form-first",
    difficulty: "intermediate",
  }),

  "bench-press": defineExercise({
    id: "bench-press",
    displayName: "Bench Press",
    aliases: ["bench-press"],
    category: "upper-body-push",
    movementPattern: "horizontal-push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "upper",
    rom: rom("elbow", [70, 175], "bar touches the chest under control before pressing to lockout"),
    tempo: tempo([1, 2.5], [0.5, 1.5], "moderate"),
    joints: joints([primary("elbow"), primary("shoulder"), stabilizer("wrist"), stabilizer("scapula")]),
    symmetry: symmetry("high", false),
    risk: risk([
      sensitivity("shoulder-impingement", "high"),
      sensitivity("wrist", "moderate"),
      sensitivity("elbow", "moderate"),
    ]),
    commonMistakes: [
      mistake("elbows-flare", "Elbows flare", "Elbows flare out toward 90° from the torso, loading the shoulder more than the chest.", "moderate"),
      mistake("bar-path", "Inconsistent bar path", "The bar drifts side to side or front-to-back instead of a straight line.", "moderate"),
      mistake("wrist-position", "Wrist position", "Wrists extend backward under load instead of stacking over the elbow.", "minor"),
      mistake("touch-point-drift", "Touch point drifting", "The bar touches a different point on the chest rep to rep.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["off the chest", "mid-range sticking point"],
    compensationPatterns: ["excessive elbow flare shifting load to the shoulder", "uneven bar path side to side"],
    coachingPriorities: ["retract and keep the shoulder blades pinned", "control the bar to the chest", "consistent touch point every rep"],
    expectedStability: "moderate",
    typicalFatiguePattern: "power-first",
    difficulty: "intermediate",
  }),

  deadlift: defineExercise({
    id: "deadlift",
    displayName: "Deadlift",
    aliases: ["deadlift"],
    category: "lower-body-compound",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes", "back"],
    secondaryMuscles: ["quads", "traps", "core"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "pull",
    bodyRegion: "full-body",
    rom: rom("hip", [40, 180], "bar starts on the floor at full hip flexion, ends at full hip/knee lockout"),
    tempo: tempo([1.5, 3], [0.8, 2], "high"),
    joints: joints([primary("hip"), primary("knee"), stabilizer("lumbar-spine"), stabilizer("forearm")]),
    symmetry: symmetry("high", false),
    risk: risk([
      sensitivity("lumbar-spine", "high"),
      sensitivity("hip", "moderate"),
    ]),
    commonMistakes: [
      mistake("back-rounding", "Back rounding", "The lumbar spine flexes under load instead of staying braced and neutral.", "major"),
      mistake("hips-shooting", "Hips shooting up", "Hips rise faster than the chest off the floor, turning the pull into a stiff-leg deadlift.", "moderate"),
      mistake("early-lockout", "Early/hyperextended lockout", "The lifter hyperextends the lower back to finish the lockout instead of the hips.", "moderate"),
      mistake("bar-drift", "Bar drifting", "The bar drifts away from the shins/thighs, extending the moment arm on the low back.", "moderate"),
    ],
    requiresLockout: true,
    bottomPositionControlled: false,
    commonWeakPoints: ["breaking the floor (initial pull)", "lockout (hip extension)"],
    compensationPatterns: ["lumbar rounding under load", "hips rising faster than the shoulders (good-morning pattern)"],
    coachingPriorities: ["brace before you pull", "keep the bar close to the shins/thighs", "hips and shoulders rise together"],
    expectedStability: "high",
    typicalFatiguePattern: "form-first",
    difficulty: "advanced",
  }),

  "overhead-press": defineExercise({
    id: "overhead-press",
    displayName: "Overhead Press",
    aliases: ["shoulder-press", "overhead-press", "military-press"],
    category: "upper-body-push",
    movementPattern: "vertical-push",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps", "core"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "upper",
    rom: rom("shoulder", [90, 180], "bar/dumbbells travel from shoulder height to full overhead lockout"),
    tempo: tempo([1, 2], [0.8, 1.8], "moderate"),
    joints: joints([primary("shoulder"), secondary("elbow"), stabilizer("core")]),
    symmetry: symmetry("high", false),
    risk: risk([
      sensitivity("shoulder-impingement", "high"),
      sensitivity("lumbar-spine", "moderate", "arching to assist the press"),
    ]),
    commonMistakes: [
      mistake("lower-back-arch", "Excessive lower-back arch", "The lifter arches the spine to help the bar clear the head.", "moderate"),
      mistake("incomplete-lockout", "Incomplete lockout", "The rep stops short of full elbow/shoulder lockout overhead.", "moderate"),
      mistake("bar-path-forward", "Bar path drifts forward", "The bar travels straight up in front instead of back over the head at lockout.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["just above the head (sticking point)", "lockout"],
    compensationPatterns: ["lumbar hyperextension to assist the press", "leg drive substituting for a strict press"],
    coachingPriorities: ["brace the core, don't arch the back", "press the bar back over the head at lockout", "full lockout every rep"],
    expectedStability: "moderate",
    typicalFatiguePattern: "power-first",
    difficulty: "intermediate",
  }),

  "barbell-row": defineExercise({
    id: "barbell-row",
    displayName: "Barbell Row",
    aliases: ["barbell-row", "row"],
    category: "upper-body-pull",
    movementPattern: "horizontal-pull",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps", "shoulders"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "pull",
    bodyRegion: "upper",
    rom: rom("shoulder", [30, 160], "bar travels from full arm extension to torso contact, elbows driving back"),
    tempo: tempo([1, 2.5], [0.6, 1.5], "moderate"),
    joints: joints([primary("shoulder"), primary("elbow"), stabilizer("lumbar-spine")]),
    symmetry: symmetry("high", false),
    risk: risk([sensitivity("lumbar-spine", "high")]),
    commonMistakes: [
      mistake("torso-rising", "Torso rising to assist", "The torso rises toward vertical to help move the bar instead of the back doing the work.", "moderate"),
      mistake("no-reset", "Not resetting", "The bar doesn't return to full arm extension between reps.", "minor"),
      mistake("shrugging", "Shrugging instead of rowing", "Traps shrug up instead of the shoulder blades retracting.", "minor"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["initiating the pull off the dead hang", "the squeeze at the top"],
    compensationPatterns: ["torso rising/using momentum to move the bar", "shrugging the traps instead of retracting the scapula"],
    coachingPriorities: ["hinge and keep the torso angle fixed", "pull elbows back, not just up", "control the descent"],
    expectedStability: "moderate",
    typicalFatiguePattern: "form-first",
    difficulty: "intermediate",
  }),

  "pull-up": defineExercise({
    id: "pull-up",
    displayName: "Pull Up",
    aliases: ["pull-ups", "pull-up", "chin-up"],
    category: "upper-body-pull",
    movementPattern: "vertical-pull",
    primaryMuscles: ["lats", "back"],
    secondaryMuscles: ["biceps", "forearms"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "pull",
    bodyRegion: "upper",
    rom: rom("shoulder", [30, 170], "dead hang at the bottom, chin clears the bar at the top"),
    tempo: tempo([1, 2.5], [0.6, 1.5], "high"),
    joints: joints([primary("shoulder"), primary("elbow"), stabilizer("core")]),
    symmetry: symmetry("high", false),
    risk: risk([sensitivity("shoulder-impingement", "moderate")]),
    commonMistakes: [
      mistake("partial-range", "Partial range", "The rep skips the dead hang at the bottom or the chin-over-bar at the top.", "moderate"),
      mistake("kipping", "Kipping/swinging", "The legs and hips swing to generate momentum instead of a strict pull.", "moderate"),
      mistake("momentum", "Using momentum", "Body English substitutes for lat/arm strength on harder reps.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["mid-pull (elbows near 90°)", "the final few inches to the bar"],
    compensationPatterns: ["kipping the hips/legs to generate momentum", "cutting the range short at the top"],
    coachingPriorities: ["start and finish every rep from a dead hang", "drive the elbows down and back", "avoid swinging"],
    expectedStability: "moderate",
    typicalFatiguePattern: "rom-first",
    difficulty: "advanced",
  }),

  "lat-pulldown": defineExercise({
    id: "lat-pulldown",
    displayName: "Lat Pulldown",
    aliases: ["lat-pulldown", "pull-down"],
    category: "upper-body-pull",
    movementPattern: "vertical-pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "shoulders"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "pull",
    bodyRegion: "upper",
    rom: rom("shoulder", [30, 170], "bar travels from full overhead arm extension to the upper chest"),
    tempo: tempo([1, 2], [0.8, 1.5], "moderate"),
    joints: joints([primary("shoulder"), secondary("elbow"), stabilizer("core")]),
    symmetry: symmetry("high", false),
    risk: risk([sensitivity("shoulder-impingement", "moderate")]),
    commonMistakes: [
      mistake("leaning-back", "Leaning back too far", "The torso leans back excessively to use bodyweight instead of the lats.", "moderate"),
      mistake("partial-range", "Partial range", "The bar doesn't reach a full stretch overhead between reps.", "minor"),
      mistake("behind-neck", "Pulling behind the neck", "The bar is pulled behind the head, straining the shoulder.", "major"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["initiating the pull from full stretch"],
    compensationPatterns: ["leaning back and using bodyweight to assist", "yanking with momentum instead of lat engagement"],
    coachingPriorities: ["drive elbows down and back, not just down", "keep the torso mostly upright", "control the return to full stretch"],
    expectedStability: "low",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  "seated-row": defineExercise({
    id: "seated-row",
    displayName: "Seated Row",
    aliases: ["seated-cable-row", "seated-row"],
    category: "upper-body-pull",
    movementPattern: "horizontal-pull",
    primaryMuscles: ["back", "lats"],
    secondaryMuscles: ["biceps", "shoulders"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "pull",
    bodyRegion: "upper",
    rom: rom("elbow", [30, 160], "arms fully extended forward to the handle at the abdomen with shoulder blades squeezed"),
    tempo: tempo([1, 2], [0.6, 1.5], "moderate"),
    joints: joints([primary("shoulder"), primary("elbow"), stabilizer("lumbar-spine")]),
    symmetry: symmetry("high", false),
    risk: risk([sensitivity("lumbar-spine", "moderate")]),
    commonMistakes: [
      mistake("leaning-back", "Leaning back excessively", "The torso rocks back to help move the handle instead of the back doing the work.", "moderate"),
      mistake("rounding-forward", "Rounding forward at the stretch", "The upper back rounds to reach further forward at the start of the rep.", "minor"),
      mistake("momentum", "Using momentum", "Body rocking substitutes for a controlled pull.", "minor"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["the squeeze at full contraction"],
    compensationPatterns: ["rocking the torso to generate momentum"],
    coachingPriorities: ["sit tall with minimal torso rock", "squeeze the shoulder blades together at the finish", "control the return"],
    expectedStability: "low",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  "leg-press": defineExercise({
    id: "leg-press",
    displayName: "Leg Press",
    aliases: ["leg-press"],
    category: "lower-body-compound",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "lower",
    rom: rom("knee", [70, 175], "knees lower to roughly 90° or until the lower back stays flat against the pad"),
    tempo: tempo([1.5, 3], [1, 2], "moderate"),
    joints: joints([primary("knee"), primary("hip"), stabilizer("ankle")]),
    symmetry: symmetry("high", false),
    risk: risk([
      sensitivity("knee-valgus", "moderate"),
      sensitivity("lumbar-spine", "moderate", "rounding off the pad at depth"),
    ]),
    commonMistakes: [
      mistake("back-rounding", "Lower back rounding off the pad", "The lower back lifts off the pad at deep flexion.", "moderate"),
      mistake("locking-hard", "Locking knees hard", "The knees snap into hard lockout at the top of every rep.", "minor"),
      mistake("partial-range", "Partial range", "The sled doesn't reach the target depth before reversing.", "moderate"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["out of the bottom"],
    compensationPatterns: ["lower back lifting off the pad at deep flexion", "knees caving under heavier loads"],
    coachingPriorities: ["keep the lower back flat against the pad", "control the descent, don't bounce the sled", "avoid locking the knees out aggressively"],
    expectedStability: "high",
    typicalFatiguePattern: "rom-first",
    difficulty: "beginner",
  }),

  "leg-extension": defineExercise({
    id: "leg-extension",
    displayName: "Leg Extension",
    aliases: ["leg-extension"],
    category: "isolation",
    movementPattern: "knee-extension",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "isolation",
    forceType: "push",
    bodyRegion: "lower",
    rom: rom("knee", [90, 180], "full knee flexion at the pad to full extension without snapping the knee"),
    tempo: tempo([1.5, 3], [0.8, 1.5], "moderate"),
    joints: joints([primary("knee"), stabilizer("hip")]),
    symmetry: symmetry("moderate", true),
    risk: risk([sensitivity("knee-valgus", "low")]),
    commonMistakes: [
      mistake("momentum", "Using momentum", "The weight is swung up instead of lifted under control.", "moderate"),
      mistake("partial-range", "Partial range", "The rep stops short of full flexion or full extension.", "minor"),
      mistake("hard-lockout", "Snapping the knee at lockout", "The knee locks out hard and fast at the top of the rep.", "moderate"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["the last few degrees of extension"],
    compensationPatterns: ["using momentum/swinging the weight", "hip lifting off the pad"],
    coachingPriorities: ["control the weight down, don't drop it", "avoid snapping the knee at lockout", "isolate the quad, minimize hip movement"],
    expectedStability: "high",
    typicalFatiguePattern: "rom-first",
    difficulty: "beginner",
  }),

  "leg-curl": defineExercise({
    id: "leg-curl",
    displayName: "Leg Curl",
    aliases: ["leg-curl"],
    category: "isolation",
    movementPattern: "knee-flexion",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "isolation",
    forceType: "pull",
    bodyRegion: "lower",
    rom: rom("knee", [0, 130], "full leg extension to heels curled toward the glutes"),
    tempo: tempo([1.5, 3], [0.8, 1.5], "moderate"),
    joints: joints([primary("knee"), stabilizer("hip")]),
    symmetry: symmetry("moderate", true),
    risk: risk([sensitivity("knee-valgus", "low")]),
    commonMistakes: [
      mistake("hips-lifting", "Hips lifting off the pad", "The hips rise to help the movement instead of the hamstrings doing the work.", "moderate"),
      mistake("momentum", "Using momentum", "The weight is swung instead of curled under control.", "minor"),
      mistake("partial-range", "Partial range", "The rep doesn't reach full extension or full flexion.", "minor"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["initiating the curl from full extension"],
    compensationPatterns: ["hips lifting off the pad to help generate momentum"],
    coachingPriorities: ["keep the hips pinned to the pad", "control the eccentric", "full range every rep"],
    expectedStability: "high",
    typicalFatiguePattern: "rom-first",
    difficulty: "beginner",
  }),

  "romanian-deadlift": defineExercise({
    id: "romanian-deadlift",
    displayName: "Romanian Deadlift",
    aliases: ["romanian-deadlift", "rdl"],
    category: "lower-body-compound",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["back", "core"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "pull",
    bodyRegion: "lower",
    rom: rom("hip", [40, 180], "hinge until the hamstring stretch limits further descent (bar around mid-shin), without rounding the back"),
    tempo: tempo([2, 3.5], [1, 2], "high"),
    joints: joints([primary("hip"), stabilizer("knee"), stabilizer("lumbar-spine")]),
    symmetry: symmetry("high", false),
    risk: risk([
      sensitivity("lumbar-spine", "high"),
      sensitivity("hip", "moderate"),
    ]),
    commonMistakes: [
      mistake("hyperextending", "Hyperextending at the top", "The lower back arches past neutral to finish the rep.", "moderate"),
      mistake("momentum", "Using momentum/bouncing", "The bar bounces off the bottom stretch instead of reversing under control.", "moderate"),
      mistake("back-rounding", "Rounding the back at depth", "The lumbar spine flexes to reach further down.", "major"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["the deepest point of the hinge"],
    compensationPatterns: ["rounding the lower back to reach further down", "bouncing out of the bottom"],
    coachingPriorities: ["hinge at the hips with a soft knee bend", "keep the bar close to the legs", "stop the descent before the back would round"],
    expectedStability: "moderate",
    typicalFatiguePattern: "form-first",
    difficulty: "intermediate",
  }),

  "hip-thrust": defineExercise({
    id: "hip-thrust",
    displayName: "Hip Thrust",
    aliases: ["hip-thrust"],
    category: "lower-body-compound",
    movementPattern: "hip-extension",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "lower",
    rom: rom("hip", [90, 180], "hips lower until just above the floor, driven up to full hip extension with the ribs down"),
    tempo: tempo([1, 2], [0.6, 1.5], "moderate"),
    joints: joints([primary("hip"), stabilizer("knee"), stabilizer("lumbar-spine")]),
    symmetry: symmetry("high", true),
    risk: risk([sensitivity("lumbar-spine", "moderate")]),
    commonMistakes: [
      mistake("lumbar-arch", "Arching the lower back", "The lower back arches to gain extra range instead of the hips extending fully.", "moderate"),
      mistake("lower-back-drive", "Using the lower back", "The lift is driven from the lumbar spine instead of the glutes.", "moderate"),
      mistake("feet-too-far", "Feet placed too far away", "Feet placement shifts load onto the hamstrings instead of the glutes.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["the last few degrees of hip extension at lockout"],
    compensationPatterns: ["lumbar hyperextension substituting for hip extension", "driving through the lower back instead of the glutes"],
    coachingPriorities: ["drive through the heels and squeeze the glutes at the top", "keep the ribs down, avoid arching the back", "full hip extension without hyperextending the spine"],
    expectedStability: "moderate",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  lunge: defineExercise({
    id: "lunge",
    displayName: "Lunge",
    aliases: ["lunges", "lunge", "walking-lunge"],
    category: "lower-body-compound",
    movementPattern: "lunge",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    planeOfMotion: "sagittal",
    laterality: "bilateral-alternating",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "lower",
    rom: rom("knee", [90, 175], "both knees reach roughly 90° with the rear knee near the floor"),
    tempo: tempo([1, 2], [0.8, 1.8], "high"),
    joints: joints([primary("knee"), primary("hip"), stabilizer("ankle")]),
    symmetry: symmetry("high", true),
    risk: risk([sensitivity("knee-valgus", "moderate")]),
    commonMistakes: [
      mistake("knee-past-toe", "Knee traveling past the toes", "The lead knee drifts well past the toes, adding shear stress at the knee.", "minor"),
      mistake("forward-lean", "Leaning forward", "The torso pitches forward instead of staying upright.", "moderate"),
      mistake("inconsistent-stride", "Inconsistent stride length", "Stride length varies rep to rep or side to side.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["out of the bottom on the lead leg"],
    compensationPatterns: ["knee caving inward on the lead leg", "torso leaning forward to compensate for balance"],
    coachingPriorities: ["keep the torso tall", "control the descent on every step", "keep stride length even side to side"],
    expectedStability: "moderate",
    typicalFatiguePattern: "stability-first",
    difficulty: "intermediate",
  }),

  "split-squat": defineExercise({
    id: "split-squat",
    displayName: "Split Squat",
    aliases: ["bulgarian-split-squat", "split-squat"],
    category: "lower-body-compound",
    movementPattern: "lunge",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    planeOfMotion: "sagittal",
    laterality: "unilateral",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "lower",
    rom: rom("knee", [90, 175], "front knee lowers to roughly 90° with the rear foot elevated"),
    tempo: tempo([1.5, 2.5], [1, 2], "high"),
    joints: joints([primary("knee"), primary("hip"), stabilizer("ankle")]),
    symmetry: symmetry("moderate", true, "inherently asymmetric loading per set — track each side separately"),
    risk: risk([sensitivity("knee-valgus", "high", "single-leg loading increases valgus demand")]),
    commonMistakes: [
      mistake("knee-valgus", "Front knee caving inward", "The front knee drifts inward under load, especially near failure.", "major"),
      mistake("forward-lean", "Leaning too far forward", "The torso pitches forward to help balance.", "moderate"),
      mistake("rear-foot-placement", "Rear foot placement", "The rear foot is placed too high or too close, shortening the working range.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["out of the bottom", "balance through the mid-range"],
    compensationPatterns: ["front knee caving inward under fatigue", "torso leaning to compensate for balance"],
    coachingPriorities: ["control the descent, don't drop", "keep the front knee tracking over the foot", "keep effort even between both legs across the set"],
    expectedStability: "low",
    typicalFatiguePattern: "stability-first",
    difficulty: "intermediate",
  }),

  "push-up": defineExercise({
    id: "push-up",
    displayName: "Push Up",
    aliases: ["push-ups", "push-up"],
    category: "upper-body-push",
    movementPattern: "horizontal-push",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders", "core"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "compound",
    forceType: "push",
    bodyRegion: "upper",
    rom: rom("elbow", [70, 175], "chest lowers to just above the floor, arms reach full extension at the top"),
    tempo: tempo([1, 2.5], [0.6, 1.5], "moderate"),
    joints: joints([primary("elbow"), primary("shoulder"), stabilizer("core")]),
    symmetry: symmetry("high", false),
    risk: risk([
      sensitivity("shoulder-impingement", "moderate"),
      sensitivity("wrist", "moderate"),
    ]),
    commonMistakes: [
      mistake("hips-sagging", "Hips sagging", "The hips sink toward the floor as the core fatigues.", "moderate"),
      mistake("hips-piking", "Hips piking up", "The hips rise up to shorten the effective range of motion.", "moderate"),
      mistake("partial-range", "Partial range", "The chest doesn't lower close enough to the floor.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["off the chest (bottom third)"],
    compensationPatterns: ["hips sagging as the core fatigues", "hips piking up to shorten the range"],
    coachingPriorities: ["keep a straight line from shoulders to ankles", "full range down to the floor", "control the descent"],
    expectedStability: "moderate",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  "dumbbell-curl": defineExercise({
    id: "dumbbell-curl",
    displayName: "Dumbbell Curl",
    aliases: ["bicep-curl", "dumbbell-curl", "curl"],
    category: "isolation",
    movementPattern: "elbow-flexion",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "isolation",
    forceType: "pull",
    bodyRegion: "upper",
    rom: rom("elbow", [10, 150], "full arm extension at the bottom to full flexion near the shoulder"),
    tempo: tempo([1.5, 2.5], [0.8, 1.5], "moderate"),
    joints: joints([primary("elbow"), stabilizer("shoulder")]),
    symmetry: symmetry("high", true),
    risk: risk([sensitivity("elbow", "low")]),
    commonMistakes: [
      mistake("swinging", "Swinging the torso", "The torso rocks to generate momentum for the curl.", "moderate"),
      mistake("partial-range", "Partial range", "The rep doesn't reach full extension or full flexion.", "minor"),
      mistake("shoulder-substitution", "Using the shoulder", "Shoulder flexion substitutes for elbow flexion.", "minor"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["mid-range (elbow near 90°)"],
    compensationPatterns: ["swinging the torso/using momentum", "shoulder flexion substituting for elbow flexion"],
    coachingPriorities: ["keep elbows pinned to the sides", "control the eccentric", "full extension at the bottom"],
    expectedStability: "high",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  "hammer-curl": defineExercise({
    id: "hammer-curl",
    displayName: "Hammer Curl",
    aliases: ["hammer-curl", "curl"],
    category: "isolation",
    movementPattern: "elbow-flexion",
    primaryMuscles: ["biceps", "forearms"],
    secondaryMuscles: [],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "isolation",
    forceType: "pull",
    bodyRegion: "upper",
    rom: rom("elbow", [10, 150], "full arm extension at the bottom to full flexion with a neutral grip"),
    tempo: tempo([1.5, 2.5], [0.8, 1.5], "moderate"),
    joints: joints([primary("elbow"), stabilizer("shoulder"), stabilizer("wrist")]),
    symmetry: symmetry("high", true),
    risk: risk([sensitivity("elbow", "low")]),
    commonMistakes: [
      mistake("swinging", "Swinging for momentum", "The torso rocks to help move the weight.", "moderate"),
      mistake("elbows-drifting", "Elbows drifting forward", "Elbows drift away from the torso during the curl.", "minor"),
      mistake("partial-range", "Partial range", "The rep doesn't reach full extension or full flexion.", "minor"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["mid-range"],
    compensationPatterns: ["elbows drifting forward away from the torso", "using body momentum"],
    coachingPriorities: ["keep elbows pinned at the sides", "maintain a neutral grip throughout", "control the descent"],
    expectedStability: "high",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  "lateral-raise": defineExercise({
    id: "lateral-raise",
    displayName: "Lateral Raise",
    aliases: ["lateral-raise"],
    category: "isolation",
    movementPattern: "shoulder-abduction",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["traps"],
    planeOfMotion: "frontal",
    laterality: "bilateral",
    mechanics: "isolation",
    forceType: "push",
    bodyRegion: "upper",
    rom: rom("shoulder", [0, 110], "arms hang at the sides, raised to roughly shoulder height without shrugging"),
    tempo: tempo([1.5, 2.5], [0.8, 1.5], "high"),
    joints: joints([primary("shoulder"), stabilizer("scapula")]),
    symmetry: symmetry("high", true),
    risk: risk([sensitivity("shoulder-impingement", "moderate")]),
    commonMistakes: [
      mistake("momentum", "Using momentum/swinging", "The weight is swung up using body momentum instead of shoulder abduction.", "moderate"),
      mistake("raising-too-high", "Raising past shoulder height", "Arms raise well above shoulder height, recruiting the traps.", "minor"),
      mistake("shrugging", "Shrugging to assist", "The traps shrug up to help lift the weight.", "moderate"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["the first few degrees off the sides"],
    compensationPatterns: ["shrugging the traps to assist the raise", "using body momentum/swinging"],
    coachingPriorities: ["lead with the elbows, not the hands", "stop at shoulder height", "control the descent, don't drop"],
    expectedStability: "high",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  "face-pull": defineExercise({
    id: "face-pull",
    displayName: "Face Pull",
    aliases: ["face-pull"],
    category: "isolation",
    movementPattern: "shoulder-external-rotation",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["back", "traps"],
    planeOfMotion: "transverse",
    laterality: "bilateral",
    mechanics: "isolation",
    forceType: "pull",
    bodyRegion: "upper",
    rom: rom("shoulder", [0, 90], "arms extended forward to rope pulled toward the face with external rotation and high elbows"),
    tempo: tempo([1, 2], [0.8, 1.5], "moderate"),
    joints: joints([primary("shoulder"), stabilizer("scapula")]),
    symmetry: symmetry("high", true),
    risk: risk([sensitivity("shoulder-impingement", "low")]),
    commonMistakes: [
      mistake("elbows-dropping", "Elbows dropping", "Elbows drop low during the pull instead of staying high.", "moderate"),
      mistake("too-heavy", "Too much weight", "Excess weight sacrifices the external rotation at the end of the pull.", "moderate"),
      mistake("rushing", "Rushing the rep", "The rep is performed too fast to control the rotation.", "minor"),
    ],
    requiresLockout: false,
    bottomPositionControlled: true,
    commonWeakPoints: ["the external rotation at the end range"],
    compensationPatterns: ["elbows dropping to shortcut the pull", "using momentum instead of controlled rotation"],
    coachingPriorities: ["keep the elbows high through the pull", "finish with external rotation, not just a row", "use a weight light enough to control the full motion"],
    expectedStability: "high",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),

  "triceps-pushdown": defineExercise({
    id: "triceps-pushdown",
    displayName: "Triceps Pushdown",
    aliases: ["tricep-pushdown", "triceps-pushdown", "pushdown"],
    category: "isolation",
    movementPattern: "elbow-extension",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    planeOfMotion: "sagittal",
    laterality: "bilateral",
    mechanics: "isolation",
    forceType: "push",
    bodyRegion: "upper",
    rom: rom("elbow", [15, 150], "elbows fixed at the sides, bar pushed from bent elbow to full extension"),
    tempo: tempo([1, 2], [0.6, 1.3], "moderate"),
    joints: joints([primary("elbow"), stabilizer("shoulder")]),
    symmetry: symmetry("high", true),
    risk: risk([sensitivity("elbow", "low")]),
    commonMistakes: [
      mistake("elbows-drifting", "Elbows drifting", "Elbows drift away from the torso during the push.", "moderate"),
      mistake("leaning-in", "Leaning bodyweight in", "Bodyweight leans into the movement to assist the push.", "minor"),
      mistake("partial-lockout", "Partial lockout", "The rep stops short of full elbow extension.", "minor"),
    ],
    requiresLockout: true,
    bottomPositionControlled: true,
    commonWeakPoints: ["full lockout at the bottom of the movement"],
    compensationPatterns: ["elbows drifting forward or outward", "leaning bodyweight into the movement to assist"],
    coachingPriorities: ["keep elbows pinned to the torso", "full extension every rep", "control the return"],
    expectedStability: "high",
    typicalFatiguePattern: "form-first",
    difficulty: "beginner",
  }),
};

export const ALL_EXERCISE_IDS: ExerciseId[] = Object.keys(EXERCISE_CATALOG) as ExerciseId[];
